title: "My CTF Writeups"
description: "Collection of writeups and notes from Capture The Flag challenges."
theme: jekyll-theme-slate

# Enable blog mode
show_excerpts: true
paginate: 5

# Site links
collections:
  categories:
    output: true
